- root: /path/to/root/

- model:
    name: ATM
    imports:
      - {name: sea_surface_temperature, grid: will provide}
      - {name: ocean_current_merid}
      - {name: ocean_current_zonal}
    exports:
      - {name: uwind}
      - {name: vwind}
    
- model:
    name: OCN
   
- mediator:
    name: MED
    imports:
      ATM: 
        - {name: uwind, remap: bilnr}
        - {name: vwind, remap: conservative}
      OCN:
        - {name: sea_surface_temperature, remap: bilnr}
       
- driver:
    name: ESM
    children: [ATM, OCN, MED]
    runseq:
      - ATM
      - OCN
      - MED
      - ATM -> OCN
      - OCN -> ATM
  