/*
 * generated by Xtext
 */
package org.earthsystemcurator.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.earthsystemcurator.ui.internal.CupidLanguageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CupidLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CupidLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CupidLanguageActivator.getInstance().getInjector(CupidLanguageActivator.ORG_EARTHSYSTEMCURATOR_CUPIDLANGUAGE);
	}
	
}
