/*
* generated by Xtext
*/
package org.earthsystemcurator;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CupidLanguageStandaloneSetup extends CupidLanguageStandaloneSetupGenerated{

	public static void doSetup() {
		new CupidLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

