/*
 * generated by Xtext
 */
package org.earthsystemmodeling.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PsycheUiModule extends org.earthsystemmodeling.ui.AbstractPsycheUiModule {
	public PsycheUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
