language: java
sudo: false

addons:
  apt:
    packages:
    - gfortran
    - libopenmpi-dev
    - openmpi-dev

before_script:
  - git clone http://git.code.sf.net/p/esmf/esmf esmf
  - cd esmf
  - export ESMF_DIR=`pwd`
  - export ESMF_COMM=openmpi
  - export ESMF_COMPILER=gfortran
  - make -j4

matrix:
  include:
#    - os: os
#      env: JAVA_HOME=$(/usr/libexec/java_home)
#    - os: linux
#      jdk: oraclejdk7
    - os: linux
      jdk: oraclejdk8
#    - os: linux
#      jdk: openjdk7

script: cd org.earthsystemmodeling.cupid.releng && mvn clean verify