language: java
sudo: false

os:
  - osx

matrix:
  include:
    - os: linux
      jdk: oraclejdk7
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: openjdk7

script: cd org.earthsystemmodeling.cupid.releng && mvn clean verify