language: java
sudo: false

cache:
  directories:
  - $HOME/.m2

addons:
  apt:
    packages:
    - gfortran
    - libopenmpi-dev
#    - openmpi-dev

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

#  - cd $HOME
#  - git clone http://git.code.sf.net/p/esmf/esmf esmf
#  - cd esmf
#  - export ESMF_DIR=`pwd`
#  - export ESMF_COMM=openmpi
#  - export ESMF_COMPILER=gfortran
#  - export ESMF_INSTALL_PREFIX=$HOME/ESMF-INSTALL
#  - make -j4
#  - make install
#  - export ESMFMKFILE=$ESMF_INSTALL_PREFIX/lib/libO/Linux.gfortran.64.openmpi.default/esmf.mk

matrix:
  include:
#    - os: os
#      env: JAVA_HOME=$(/usr/libexec/java_home)
#    - os: linux
#      jdk: oraclejdk7
    - os: linux
      jdk: oraclejdk8
#    - os: linux
#      jdk: openjdk7

script: cd $TRAVIS_BUILD_DIR/org.earthsystemmodeling.cupid.releng && mvn clean verify