language: java
sudo: true

cache:
  directories:
  - $HOME/.m2
  - $HOME/esmf
  - $HOME/ESMF-INSTALL
  - $HOME/openmpi-1.10.7-install
  - $HOME/openmpi-2.1.2-install

# required because of OpenJDK bug https://github.com/travis-ci/travis-ci/issues/5227  
addons:
  hostname: cupidhost

#addons:
#  apt:
#    packages:
#    - gfortran
#    - libopenmpi-dev
#    - openmpi-dev

before_script:
# Linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gfortran libopenmpi-dev openmpi-bin openjdk-7-jdk -y ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0  ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start  ;fi

# OSX
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then $TRAVIS_BUILD_DIR/build_mpi.sh ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$HOME/openmpi-1.10.7-install/bin:$PATH ;fi

# common
  - if [[ ! -d "$HOME/ESMF-INSTALL/ESMF_7_0_0/lib" ]]; then $TRAVIS_BUILD_DIR/build_esmf.sh ESMF_7_0_0 openmpi ;fi
#  - if [[ ! -d "$HOME/ESMF-INSTALL/ESMF_7_1_0_beta_snapshot_34/lib" ]]; then $TRAVIS_BUILD_DIR/build_esmf.sh ESMF_7_1_0_beta_snapshot_34 openmpi ;fi
  - export ESMF_INSTALL_ROOT=$HOME/ESMF-INSTALL

osx_image: xcode8

matrix:
  include:
    - os: osx
      env: JAVA_HOME=$(/usr/libexec/java_home)
    - os: linux
      jdk: oraclejdk8

script: cd $TRAVIS_BUILD_DIR/org.earthsystemmodeling.cupid.releng && mvn clean 
