language: java
sudo: false

addons:
  apt:
    packages:
    - gfortran
    - libopenmpi-dev
    - openmpi-dev

matrix:
  include:
#    - os: os
#      env: JAVA_HOME=$(/usr/libexec/java_home)
#    - os: linux
#      jdk: oraclejdk7
    - os: linux
      jdk: oraclejdk8
#    - os: linux
#      jdk: openjdk7

script: cd org.earthsystemmodeling.cupid.releng && mvn clean verify