/*
* generated by Xtext
*/
package org.earthsystemmodeling.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PsycheAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/earthsystemmodeling/parser/antlr/internal/InternalPsyche.tokens");
	}
}
