/*
* generated by Xtext
*/
package org.earthsystemmodeling;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PsycheUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.earthsystemmodeling.ui.internal.PsycheActivator.getInstance().getInjector("org.earthsystemmodeling.Psyche");
	}
	
}
