/*
* generated by Xtext
*/
package org.earthsystemmodeling;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PsycheStandaloneSetup extends PsycheStandaloneSetupGenerated{

	public static void doSetup() {
		new PsycheStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

