<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="nuopc" nsURI="http://www.earthsystemcurator.org/nuopc" nsPrefix="nuopc">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eAnnotations source="http://www.earthsystemcog.org/projects/nuopc">
      <details key="query" value="module"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true">
      <eAnnotations source="http://www.earthsystemcog.org/projects/nuopc">
        <details key="query" value="moduleName"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usesAllImports" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definesSetServices" upperBound="-1"
        eType="#//ModelDefinesSetServices" containment="true" eKeys="#//ModelDefinesSetServices/name">
      <eAnnotations source="http://www.earthsystemcog.org/projects/nuopc">
        <details key="query" value="subroutine: *(type(ESMF_GridComp), integer)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="singlePublicSubroutine"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.earthsystemcog.org/projects/nuopc">
        <details key="query" value="hasSinglePublicMember"/>
        <details key="transform" value="addPublicMember"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementsInitP1" eType="#//ModelImplementsInitP1"
        containment="true">
      <eAnnotations source="http://www.earthsystemcog.org/projects/nuopc">
        <details key="query" value="subroutine: *(type(ESMF_GridComp), type(ESMF_State), type(ESMF_State), type(ESMF_Clock), integer)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementsInitP2" eType="#//ModelImplementsInitP2"
        containment="true">
      <eAnnotations source="http://www.earthsystemcog.org/projects/nuopc">
        <details key="query" value="subroutine: *(type(ESMF_GridComp), type(ESMF_State), type(ESMF_State), type(ESMF_Clock), integer)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelDefinesSetServices">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true">
      <eAnnotations source="http://www.earthsystemcog.org/projects/nuopc">
        <details key="query" value="subroutineName"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paramName_gcomp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paramName_rc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="callsGenericSetServices"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.earthsystemcog.org/projects/nuopc">
        <details key="query" value="calls: routine_SetServices"/>
        <details key="essential" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="callsSetEntryPointPhase1"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.earthsystemcog.org/projects/nuopc">
        <details key="query" value="calls: ESMF_GridCompSetEntryPoint"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="callsSetEntryPointPhase2"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.earthsystemcog.org/projects/nuopc">
        <details key="query" value="calls: ESMF_GridCompSetEntryPoint"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachesMethod" upperBound="-1"
        eType="#//AttachesMethod" containment="true"/>
    <eGenericSuperTypes eClassifier="#//Candidate">
      <eTypeArguments eClassifier="#//ModelDefinesSetServices"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelImplementsInitP1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true">
      <eAnnotations source="http://www.earthsystemcog.org/projects/nuopc">
        <details key="query" value="subroutineName"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="advertisesImportField"
        upperBound="-1" eType="#//AdvertisesImportField" containment="true">
      <eAnnotations source="http://www.earthsystemcog.org/projects/nuopc">
        <details key="query" value="call: NUOPC_StateAdvertiseField"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="advertisesExportField"
        upperBound="-1" eType="#//AdvertisesExportField" containment="true">
      <eAnnotations source="http://www.earthsystemcog.org/projects/nuopc">
        <details key="query" value="call: NUOPC_StateAdvertiseField"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelImplementsInitP2">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true">
      <eAnnotations source="http://www.earthsystemcog.org/projects/nuopc">
        <details key="query" value="subroutineName"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdvertisesImportField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addsToImportState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.earthsystemcog.org/projects/nuopc">
        <details key="query" value="argByIndex: 1 sameAs: ../importStateParam"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="standardName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.earthsystemcog.org/projects/nuopc">
        <details key="query" value="argByKeyword: StandardName"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdvertisesExportField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="standardName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.earthsystemcog.org/projects/nuopc">
        <details key="query" value="argByKeyword: StandardName"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttachesMethod">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comparable" instanceClassName="java.lang.Comparable"
      abstract="true" interface="true">
    <eTypeParameters name="c"/>
    <eOperations name="compareTo" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eParameters name="other" lowerBound="1">
        <eGenericType eTypeParameter="#//Comparable/c"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Candidate" abstract="true" interface="true">
    <eTypeParameters name="c"/>
    <eOperations name="score" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eGenericSuperTypes eClassifier="#//Comparable">
      <eTypeArguments eTypeParameter="#//Candidate/c"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
