/*
 * generated by Xtext
 */
package org.earthsystemmodeling.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractCupidLanguageValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.earthsystemmodeling.cupid.CupidPackage.eINSTANCE);
		return result;
	}
}
