/*
 * generated by Xtext
 */
package org.earthsystemmodeling;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CupidLanguageRuntimeModule extends org.earthsystemmodeling.AbstractCupidLanguageRuntimeModule {

}
