/*
 * generated by Xtext
 */
package org.earthsystemcurator.ui.contentassist

import org.earthsystemcurator.ui.contentassist.AbstractCupidLanguageProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CupidLanguageProposalProvider extends AbstractCupidLanguageProposalProvider {
}
