<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simple" nsURI="http://www.earthsystemcurator.org/cupid/test/Simple"
    nsPrefix="simple">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EDataType" name="AST__Module" instanceClassName="org.eclipse.photran.internal.core.parser.ASTModuleNode"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AST__Call" instanceClassName="org.eclipse.photran.internal.core.parser.ASTCallStmtNode"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AST__Subroutine" instanceClassName="org.eclipse.photran.internal.core.parser.ASTSubroutineSubprogramNode"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AST__UsesModule" instanceClassName="org.eclipse.photran.internal.core.parser.ASTUseStmtNode"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EClass" name="MappedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapsTo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopConcept" eSuperTypes="#//MappedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" ordered="false"
        upperBound="-1" eType="#//TopConcept__Modules" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopConcept__Modules" eSuperTypes="#//MappedElement"/>
</ecore:EPackage>
