/*
 * generated by Xtext
 */
package org.earthsystemcurator.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CupidLanguageUiModule extends org.earthsystemcurator.ui.AbstractCupidLanguageUiModule {
	public CupidLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
