/**
 */
package org.earthsystemcurator.cupid.nuopc.fsml.nuopc.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.earthsystemcurator.cupid.nuopc.fsml.nuopc.util.NUOPCAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class NUOPCItemProviderAdapterFactory extends NUOPCAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NUOPCItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.Top} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TopItemProvider topItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.Top}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTopAdapter() {
		if (topItemProvider == null) {
			topItemProvider = new TopItemProvider(this);
		}

		return topItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCApplication} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCApplicationItemProvider nuopcApplicationItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCApplication}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCApplicationAdapter() {
		if (nuopcApplicationItemProvider == null) {
			nuopcApplicationItemProvider = new NUOPCApplicationItemProvider(this);
		}

		return nuopcApplicationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCModelItemProvider nuopcModelItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCModelAdapter() {
		if (nuopcModelItemProvider == null) {
			nuopcModelItemProvider = new NUOPCModelItemProvider(this);
		}

		return nuopcModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCModel__GenericImports} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCModel__GenericImportsItemProvider nuopcModel__GenericImportsItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCModel__GenericImports}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCModel__GenericImportsAdapter() {
		if (nuopcModel__GenericImportsItemProvider == null) {
			nuopcModel__GenericImportsItemProvider = new NUOPCModel__GenericImportsItemProvider(this);
		}

		return nuopcModel__GenericImportsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCModel__Init} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCModel__InitItemProvider nuopcModel__InitItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCModel__Init}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCModel__InitAdapter() {
		if (nuopcModel__InitItemProvider == null) {
			nuopcModel__InitItemProvider = new NUOPCModel__InitItemProvider(this);
		}

		return nuopcModel__InitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCModel__ImplementsSetServices} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCModel__ImplementsSetServicesItemProvider nuopcModel__ImplementsSetServicesItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCModel__ImplementsSetServices}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCModel__ImplementsSetServicesAdapter() {
		if (nuopcModel__ImplementsSetServicesItemProvider == null) {
			nuopcModel__ImplementsSetServicesItemProvider = new NUOPCModel__ImplementsSetServicesItemProvider(this);
		}

		return nuopcModel__ImplementsSetServicesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCModel__ImplementsInitP1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCModel__ImplementsInitP1ItemProvider nuopcModel__ImplementsInitP1ItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCModel__ImplementsInitP1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCModel__ImplementsInitP1Adapter() {
		if (nuopcModel__ImplementsInitP1ItemProvider == null) {
			nuopcModel__ImplementsInitP1ItemProvider = new NUOPCModel__ImplementsInitP1ItemProvider(this);
		}

		return nuopcModel__ImplementsInitP1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCModel__ImplementsInitP2} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCModel__ImplementsInitP2ItemProvider nuopcModel__ImplementsInitP2ItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCModel__ImplementsInitP2}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCModel__ImplementsInitP2Adapter() {
		if (nuopcModel__ImplementsInitP2ItemProvider == null) {
			nuopcModel__ImplementsInitP2ItemProvider = new NUOPCModel__ImplementsInitP2ItemProvider(this);
		}

		return nuopcModel__ImplementsInitP2ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCModel__AdvertisesImportField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCModel__AdvertisesImportFieldItemProvider nuopcModel__AdvertisesImportFieldItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCModel__AdvertisesImportField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCModel__AdvertisesImportFieldAdapter() {
		if (nuopcModel__AdvertisesImportFieldItemProvider == null) {
			nuopcModel__AdvertisesImportFieldItemProvider = new NUOPCModel__AdvertisesImportFieldItemProvider(this);
		}

		return nuopcModel__AdvertisesImportFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCModel__AdvertisesExportField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCModel__AdvertisesExportFieldItemProvider nuopcModel__AdvertisesExportFieldItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCModel__AdvertisesExportField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCModel__AdvertisesExportFieldAdapter() {
		if (nuopcModel__AdvertisesExportFieldItemProvider == null) {
			nuopcModel__AdvertisesExportFieldItemProvider = new NUOPCModel__AdvertisesExportFieldItemProvider(this);
		}

		return nuopcModel__AdvertisesExportFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCModel__RealizesImportField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCModel__RealizesImportFieldItemProvider nuopcModel__RealizesImportFieldItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCModel__RealizesImportField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCModel__RealizesImportFieldAdapter() {
		if (nuopcModel__RealizesImportFieldItemProvider == null) {
			nuopcModel__RealizesImportFieldItemProvider = new NUOPCModel__RealizesImportFieldItemProvider(this);
		}

		return nuopcModel__RealizesImportFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCModel__RealizesExportField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCModel__RealizesExportFieldItemProvider nuopcModel__RealizesExportFieldItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCModel__RealizesExportField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCModel__RealizesExportFieldAdapter() {
		if (nuopcModel__RealizesExportFieldItemProvider == null) {
			nuopcModel__RealizesExportFieldItemProvider = new NUOPCModel__RealizesExportFieldItemProvider(this);
		}

		return nuopcModel__RealizesExportFieldItemProvider;
	}

	
	
	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriver} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCDriverItemProvider nuopcDriverItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriver}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCDriverAdapter() {
		if (nuopcDriverItemProvider == null) {
			nuopcDriverItemProvider = new NUOPCDriverItemProvider(this);
		}

		return nuopcDriverItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriver__GenericImports} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCDriver__GenericImportsItemProvider nuopcDriver__GenericImportsItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriver__GenericImports}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCDriver__GenericImportsAdapter() {
		if (nuopcDriver__GenericImportsItemProvider == null) {
			nuopcDriver__GenericImportsItemProvider = new NUOPCDriver__GenericImportsItemProvider(this);
		}

		return nuopcDriver__GenericImportsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriver__ModelImports} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCDriver__ModelImportsItemProvider nuopcDriver__ModelImportsItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriver__ModelImports}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCDriver__ModelImportsAdapter() {
		if (nuopcDriver__ModelImportsItemProvider == null) {
			nuopcDriver__ModelImportsItemProvider = new NUOPCDriver__ModelImportsItemProvider(this);
		}

		return nuopcDriver__ModelImportsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriver__ModelImports__ModelImport} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCDriver__ModelImports__ModelImportItemProvider nuopcDriver__ModelImports__ModelImportItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriver__ModelImports__ModelImport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCDriver__ModelImports__ModelImportAdapter() {
		if (nuopcDriver__ModelImports__ModelImportItemProvider == null) {
			nuopcDriver__ModelImports__ModelImportItemProvider = new NUOPCDriver__ModelImports__ModelImportItemProvider(this);
		}

		return nuopcDriver__ModelImports__ModelImportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriver__ConnectorImports} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCDriver__ConnectorImportsItemProvider nuopcDriver__ConnectorImportsItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriver__ConnectorImports}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCDriver__ConnectorImportsAdapter() {
		if (nuopcDriver__ConnectorImportsItemProvider == null) {
			nuopcDriver__ConnectorImportsItemProvider = new NUOPCDriver__ConnectorImportsItemProvider(this);
		}

		return nuopcDriver__ConnectorImportsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriver__ConnectorImports__ConnectorImport} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCDriver__ConnectorImports__ConnectorImportItemProvider nuopcDriver__ConnectorImports__ConnectorImportItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriver__ConnectorImports__ConnectorImport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCDriver__ConnectorImports__ConnectorImportAdapter() {
		if (nuopcDriver__ConnectorImports__ConnectorImportItemProvider == null) {
			nuopcDriver__ConnectorImports__ConnectorImportItemProvider = new NUOPCDriver__ConnectorImports__ConnectorImportItemProvider(this);
		}

		return nuopcDriver__ConnectorImports__ConnectorImportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriver__ImplementsSetServices} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCDriver__ImplementsSetServicesItemProvider nuopcDriver__ImplementsSetServicesItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriver__ImplementsSetServices}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCDriver__ImplementsSetServicesAdapter() {
		if (nuopcDriver__ImplementsSetServicesItemProvider == null) {
			nuopcDriver__ImplementsSetServicesItemProvider = new NUOPCDriver__ImplementsSetServicesItemProvider(this);
		}

		return nuopcDriver__ImplementsSetServicesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriver__ImplementsSetModelCount} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCDriver__ImplementsSetModelCountItemProvider nuopcDriver__ImplementsSetModelCountItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriver__ImplementsSetModelCount}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCDriver__ImplementsSetModelCountAdapter() {
		if (nuopcDriver__ImplementsSetModelCountItemProvider == null) {
			nuopcDriver__ImplementsSetModelCountItemProvider = new NUOPCDriver__ImplementsSetModelCountItemProvider(this);
		}

		return nuopcDriver__ImplementsSetModelCountItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriver__ImplementsSetModelServices} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCDriver__ImplementsSetModelServicesItemProvider nuopcDriver__ImplementsSetModelServicesItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriver__ImplementsSetModelServices}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCDriver__ImplementsSetModelServicesAdapter() {
		if (nuopcDriver__ImplementsSetModelServicesItemProvider == null) {
			nuopcDriver__ImplementsSetModelServicesItemProvider = new NUOPCDriver__ImplementsSetModelServicesItemProvider(this);
		}

		return nuopcDriver__ImplementsSetModelServicesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriverAtmOcn} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCDriverAtmOcnItemProvider nuopcDriverAtmOcnItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriverAtmOcn}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCDriverAtmOcnAdapter() {
		if (nuopcDriverAtmOcnItemProvider == null) {
			nuopcDriverAtmOcnItemProvider = new NUOPCDriverAtmOcnItemProvider(this);
		}

		return nuopcDriverAtmOcnItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriverAtmOcn__GenericImports} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCDriverAtmOcn__GenericImportsItemProvider nuopcDriverAtmOcn__GenericImportsItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriverAtmOcn__GenericImports}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCDriverAtmOcn__GenericImportsAdapter() {
		if (nuopcDriverAtmOcn__GenericImportsItemProvider == null) {
			nuopcDriverAtmOcn__GenericImportsItemProvider = new NUOPCDriverAtmOcn__GenericImportsItemProvider(this);
		}

		return nuopcDriverAtmOcn__GenericImportsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriverAtmOcn__ModelImports} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCDriverAtmOcn__ModelImportsItemProvider nuopcDriverAtmOcn__ModelImportsItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriverAtmOcn__ModelImports}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCDriverAtmOcn__ModelImportsAdapter() {
		if (nuopcDriverAtmOcn__ModelImportsItemProvider == null) {
			nuopcDriverAtmOcn__ModelImportsItemProvider = new NUOPCDriverAtmOcn__ModelImportsItemProvider(this);
		}

		return nuopcDriverAtmOcn__ModelImportsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriverAtmOcn__ImplementsSetServices} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCDriverAtmOcn__ImplementsSetServicesItemProvider nuopcDriverAtmOcn__ImplementsSetServicesItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriverAtmOcn__ImplementsSetServices}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCDriverAtmOcn__ImplementsSetServicesAdapter() {
		if (nuopcDriverAtmOcn__ImplementsSetServicesItemProvider == null) {
			nuopcDriverAtmOcn__ImplementsSetServicesItemProvider = new NUOPCDriverAtmOcn__ImplementsSetServicesItemProvider(this);
		}

		return nuopcDriverAtmOcn__ImplementsSetServicesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriverAtmOcn__ImplementsSetModelCount} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCDriverAtmOcn__ImplementsSetModelCountItemProvider nuopcDriverAtmOcn__ImplementsSetModelCountItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriverAtmOcn__ImplementsSetModelCount}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCDriverAtmOcn__ImplementsSetModelCountAdapter() {
		if (nuopcDriverAtmOcn__ImplementsSetModelCountItemProvider == null) {
			nuopcDriverAtmOcn__ImplementsSetModelCountItemProvider = new NUOPCDriverAtmOcn__ImplementsSetModelCountItemProvider(this);
		}

		return nuopcDriverAtmOcn__ImplementsSetModelCountItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriverAtmOcn__ImplementsSetModelServices} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCDriverAtmOcn__ImplementsSetModelServicesItemProvider nuopcDriverAtmOcn__ImplementsSetModelServicesItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriverAtmOcn__ImplementsSetModelServices}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCDriverAtmOcn__ImplementsSetModelServicesAdapter() {
		if (nuopcDriverAtmOcn__ImplementsSetModelServicesItemProvider == null) {
			nuopcDriverAtmOcn__ImplementsSetModelServicesItemProvider = new NUOPCDriverAtmOcn__ImplementsSetModelServicesItemProvider(this);
		}

		return nuopcDriverAtmOcn__ImplementsSetModelServicesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriverAtmOcn__ImplementsSetModelPetLists} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCDriverAtmOcn__ImplementsSetModelPetListsItemProvider nuopcDriverAtmOcn__ImplementsSetModelPetListsItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriverAtmOcn__ImplementsSetModelPetLists}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCDriverAtmOcn__ImplementsSetModelPetListsAdapter() {
		if (nuopcDriverAtmOcn__ImplementsSetModelPetListsItemProvider == null) {
			nuopcDriverAtmOcn__ImplementsSetModelPetListsItemProvider = new NUOPCDriverAtmOcn__ImplementsSetModelPetListsItemProvider(this);
		}

		return nuopcDriverAtmOcn__ImplementsSetModelPetListsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriverAtmOcn__ModelImports__ModelImport} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCDriverAtmOcn__ModelImports__ModelImportItemProvider nuopcDriverAtmOcn__ModelImports__ModelImportItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCDriverAtmOcn__ModelImports__ModelImport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCDriverAtmOcn__ModelImports__ModelImportAdapter() {
		if (nuopcDriverAtmOcn__ModelImports__ModelImportItemProvider == null) {
			nuopcDriverAtmOcn__ModelImports__ModelImportItemProvider = new NUOPCDriverAtmOcn__ModelImports__ModelImportItemProvider(this);
		}

		return nuopcDriverAtmOcn__ModelImports__ModelImportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.CallsGenericSetServices} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CallsGenericSetServicesItemProvider callsGenericSetServicesItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.CallsGenericSetServices}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCallsGenericSetServicesAdapter() {
		if (callsGenericSetServicesItemProvider == null) {
			callsGenericSetServicesItemProvider = new CallsGenericSetServicesItemProvider(this);
		}

		return callsGenericSetServicesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.CallsSetEntryPoint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CallsSetEntryPointItemProvider callsSetEntryPointItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.CallsSetEntryPoint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCallsSetEntryPointAdapter() {
		if (callsSetEntryPointItemProvider == null) {
			callsSetEntryPointItemProvider = new CallsSetEntryPointItemProvider(this);
		}

		return callsSetEntryPointItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.AttachesMethod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttachesMethodItemProvider attachesMethodItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.AttachesMethod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttachesMethodAdapter() {
		if (attachesMethodItemProvider == null) {
			attachesMethodItemProvider = new AttachesMethodItemProvider(this);
		}

		return attachesMethodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.SetModelServices} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SetModelServicesItemProvider setModelServicesItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.SetModelServices}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSetModelServicesAdapter() {
		if (setModelServicesItemProvider == null) {
			setModelServicesItemProvider = new SetModelServicesItemProvider(this);
		}

		return setModelServicesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.SetCouplerServices} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SetCouplerServicesItemProvider setCouplerServicesItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.SetCouplerServices}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSetCouplerServicesAdapter() {
		if (setCouplerServicesItemProvider == null) {
			setCouplerServicesItemProvider = new SetCouplerServicesItemProvider(this);
		}

		return setCouplerServicesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.GetsInternalState} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GetsInternalStateItemProvider getsInternalStateItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.GetsInternalState}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGetsInternalStateAdapter() {
		if (getsInternalStateItemProvider == null) {
			getsInternalStateItemProvider = new GetsInternalStateItemProvider(this);
		}

		return getsInternalStateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCMediatorItemProvider nuopcMediatorItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCMediatorAdapter() {
		if (nuopcMediatorItemProvider == null) {
			nuopcMediatorItemProvider = new NUOPCMediatorItemProvider(this);
		}

		return nuopcMediatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator__GenericImports} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCMediator__GenericImportsItemProvider nuopcMediator__GenericImportsItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator__GenericImports}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCMediator__GenericImportsAdapter() {
		if (nuopcMediator__GenericImportsItemProvider == null) {
			nuopcMediator__GenericImportsItemProvider = new NUOPCMediator__GenericImportsItemProvider(this);
		}

		return nuopcMediator__GenericImportsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator__Init} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCMediator__InitItemProvider nuopcMediator__InitItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator__Init}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCMediator__InitAdapter() {
		if (nuopcMediator__InitItemProvider == null) {
			nuopcMediator__InitItemProvider = new NUOPCMediator__InitItemProvider(this);
		}

		return nuopcMediator__InitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator__ImplementsSetServices} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCMediator__ImplementsSetServicesItemProvider nuopcMediator__ImplementsSetServicesItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator__ImplementsSetServices}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCMediator__ImplementsSetServicesAdapter() {
		if (nuopcMediator__ImplementsSetServicesItemProvider == null) {
			nuopcMediator__ImplementsSetServicesItemProvider = new NUOPCMediator__ImplementsSetServicesItemProvider(this);
		}

		return nuopcMediator__ImplementsSetServicesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator__ImplementsInitP1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCMediator__ImplementsInitP1ItemProvider nuopcMediator__ImplementsInitP1ItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator__ImplementsInitP1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCMediator__ImplementsInitP1Adapter() {
		if (nuopcMediator__ImplementsInitP1ItemProvider == null) {
			nuopcMediator__ImplementsInitP1ItemProvider = new NUOPCMediator__ImplementsInitP1ItemProvider(this);
		}

		return nuopcMediator__ImplementsInitP1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator__ImplementsInitP2} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCMediator__ImplementsInitP2ItemProvider nuopcMediator__ImplementsInitP2ItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator__ImplementsInitP2}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCMediator__ImplementsInitP2Adapter() {
		if (nuopcMediator__ImplementsInitP2ItemProvider == null) {
			nuopcMediator__ImplementsInitP2ItemProvider = new NUOPCMediator__ImplementsInitP2ItemProvider(this);
		}

		return nuopcMediator__ImplementsInitP2ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator__AdvertisesImportField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCMediator__AdvertisesImportFieldItemProvider nuopcMediator__AdvertisesImportFieldItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator__AdvertisesImportField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCMediator__AdvertisesImportFieldAdapter() {
		if (nuopcMediator__AdvertisesImportFieldItemProvider == null) {
			nuopcMediator__AdvertisesImportFieldItemProvider = new NUOPCMediator__AdvertisesImportFieldItemProvider(this);
		}

		return nuopcMediator__AdvertisesImportFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator__AdvertisesExportField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCMediator__AdvertisesExportFieldItemProvider nuopcMediator__AdvertisesExportFieldItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator__AdvertisesExportField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCMediator__AdvertisesExportFieldAdapter() {
		if (nuopcMediator__AdvertisesExportFieldItemProvider == null) {
			nuopcMediator__AdvertisesExportFieldItemProvider = new NUOPCMediator__AdvertisesExportFieldItemProvider(this);
		}

		return nuopcMediator__AdvertisesExportFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator__RealizesImportField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCMediator__RealizesImportFieldItemProvider nuopcMediator__RealizesImportFieldItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator__RealizesImportField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCMediator__RealizesImportFieldAdapter() {
		if (nuopcMediator__RealizesImportFieldItemProvider == null) {
			nuopcMediator__RealizesImportFieldItemProvider = new NUOPCMediator__RealizesImportFieldItemProvider(this);
		}

		return nuopcMediator__RealizesImportFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator__RealizesExportField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCMediator__RealizesExportFieldItemProvider nuopcMediator__RealizesExportFieldItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator__RealizesExportField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCMediator__RealizesExportFieldAdapter() {
		if (nuopcMediator__RealizesExportFieldItemProvider == null) {
			nuopcMediator__RealizesExportFieldItemProvider = new NUOPCMediator__RealizesExportFieldItemProvider(this);
		}

		return nuopcMediator__RealizesExportFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator__ModelAdvance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NUOPCMediator__ModelAdvanceItemProvider nuopcMediator__ModelAdvanceItemProvider;

	/**
	 * This creates an adapter for a {@link org.earthsystemcurator.cupid.nuopc.fsml.nuopc.NUOPCMediator__ModelAdvance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNUOPCMediator__ModelAdvanceAdapter() {
		if (nuopcMediator__ModelAdvanceItemProvider == null) {
			nuopcMediator__ModelAdvanceItemProvider = new NUOPCMediator__ModelAdvanceItemProvider(this);
		}

		return nuopcMediator__ModelAdvanceItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (topItemProvider != null) topItemProvider.dispose();
		if (nuopcApplicationItemProvider != null) nuopcApplicationItemProvider.dispose();
		if (nuopcModelItemProvider != null) nuopcModelItemProvider.dispose();
		if (nuopcModel__GenericImportsItemProvider != null) nuopcModel__GenericImportsItemProvider.dispose();
		if (nuopcModel__InitItemProvider != null) nuopcModel__InitItemProvider.dispose();
		if (nuopcModel__ImplementsSetServicesItemProvider != null) nuopcModel__ImplementsSetServicesItemProvider.dispose();
		if (nuopcModel__ImplementsInitP1ItemProvider != null) nuopcModel__ImplementsInitP1ItemProvider.dispose();
		if (nuopcModel__ImplementsInitP2ItemProvider != null) nuopcModel__ImplementsInitP2ItemProvider.dispose();
		if (nuopcModel__AdvertisesImportFieldItemProvider != null) nuopcModel__AdvertisesImportFieldItemProvider.dispose();
		if (nuopcModel__AdvertisesExportFieldItemProvider != null) nuopcModel__AdvertisesExportFieldItemProvider.dispose();
		if (nuopcModel__RealizesImportFieldItemProvider != null) nuopcModel__RealizesImportFieldItemProvider.dispose();
		if (nuopcModel__RealizesExportFieldItemProvider != null) nuopcModel__RealizesExportFieldItemProvider.dispose();
		if (nuopcDriverItemProvider != null) nuopcDriverItemProvider.dispose();
		if (nuopcDriver__GenericImportsItemProvider != null) nuopcDriver__GenericImportsItemProvider.dispose();
		if (nuopcDriver__ModelImportsItemProvider != null) nuopcDriver__ModelImportsItemProvider.dispose();
		if (nuopcDriver__ModelImports__ModelImportItemProvider != null) nuopcDriver__ModelImports__ModelImportItemProvider.dispose();
		if (nuopcDriver__ConnectorImportsItemProvider != null) nuopcDriver__ConnectorImportsItemProvider.dispose();
		if (nuopcDriver__ConnectorImports__ConnectorImportItemProvider != null) nuopcDriver__ConnectorImports__ConnectorImportItemProvider.dispose();
		if (nuopcDriver__ImplementsSetServicesItemProvider != null) nuopcDriver__ImplementsSetServicesItemProvider.dispose();
		if (nuopcDriver__ImplementsSetModelCountItemProvider != null) nuopcDriver__ImplementsSetModelCountItemProvider.dispose();
		if (nuopcDriver__ImplementsSetModelServicesItemProvider != null) nuopcDriver__ImplementsSetModelServicesItemProvider.dispose();
		if (nuopcDriverAtmOcnItemProvider != null) nuopcDriverAtmOcnItemProvider.dispose();
		if (nuopcDriverAtmOcn__GenericImportsItemProvider != null) nuopcDriverAtmOcn__GenericImportsItemProvider.dispose();
		if (nuopcDriverAtmOcn__ModelImportsItemProvider != null) nuopcDriverAtmOcn__ModelImportsItemProvider.dispose();
		if (nuopcDriverAtmOcn__ImplementsSetServicesItemProvider != null) nuopcDriverAtmOcn__ImplementsSetServicesItemProvider.dispose();
		if (nuopcDriverAtmOcn__ImplementsSetModelCountItemProvider != null) nuopcDriverAtmOcn__ImplementsSetModelCountItemProvider.dispose();
		if (nuopcDriverAtmOcn__ImplementsSetModelServicesItemProvider != null) nuopcDriverAtmOcn__ImplementsSetModelServicesItemProvider.dispose();
		if (nuopcDriverAtmOcn__ImplementsSetModelPetListsItemProvider != null) nuopcDriverAtmOcn__ImplementsSetModelPetListsItemProvider.dispose();
		if (nuopcDriverAtmOcn__ModelImports__ModelImportItemProvider != null) nuopcDriverAtmOcn__ModelImports__ModelImportItemProvider.dispose();
		if (callsGenericSetServicesItemProvider != null) callsGenericSetServicesItemProvider.dispose();
		if (callsSetEntryPointItemProvider != null) callsSetEntryPointItemProvider.dispose();
		if (attachesMethodItemProvider != null) attachesMethodItemProvider.dispose();
		if (setModelServicesItemProvider != null) setModelServicesItemProvider.dispose();
		if (setCouplerServicesItemProvider != null) setCouplerServicesItemProvider.dispose();
		if (getsInternalStateItemProvider != null) getsInternalStateItemProvider.dispose();
		if (nuopcMediatorItemProvider != null) nuopcMediatorItemProvider.dispose();
		if (nuopcMediator__GenericImportsItemProvider != null) nuopcMediator__GenericImportsItemProvider.dispose();
		if (nuopcMediator__InitItemProvider != null) nuopcMediator__InitItemProvider.dispose();
		if (nuopcMediator__ImplementsSetServicesItemProvider != null) nuopcMediator__ImplementsSetServicesItemProvider.dispose();
		if (nuopcMediator__ImplementsInitP1ItemProvider != null) nuopcMediator__ImplementsInitP1ItemProvider.dispose();
		if (nuopcMediator__ImplementsInitP2ItemProvider != null) nuopcMediator__ImplementsInitP2ItemProvider.dispose();
		if (nuopcMediator__AdvertisesImportFieldItemProvider != null) nuopcMediator__AdvertisesImportFieldItemProvider.dispose();
		if (nuopcMediator__AdvertisesExportFieldItemProvider != null) nuopcMediator__AdvertisesExportFieldItemProvider.dispose();
		if (nuopcMediator__RealizesImportFieldItemProvider != null) nuopcMediator__RealizesImportFieldItemProvider.dispose();
		if (nuopcMediator__RealizesExportFieldItemProvider != null) nuopcMediator__RealizesExportFieldItemProvider.dispose();
		if (nuopcMediator__ModelAdvanceItemProvider != null) nuopcMediator__ModelAdvanceItemProvider.dispose();
	}

}
