<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="createsyncproject" nsURI="http://www.eclipse.org/oomph/setup/createsyncproject/1.0"
    nsPrefix="createsyncproject">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="schemaLocation.http" value="http://git.eclipse.org/c/oomph/org.eclipse.oomph.createsyncproject/plain/setups/models/CreateSyncProject.ecore"/>
    <details key="schemaLocation" value="file:/home/rocky/eclipse/oomph-master/git/org.eclipse.oomph/plugins/org.eclipse.oomph.setup.createsyncproject/model/CreateSyncProject.ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/oomph/setup/Enablement">
    <details key="variableName" value="setup.createsyncproject.p2"/>
    <details key="repository" value="${oomph.update.url}"/>
    <details key="installableUnits" value="org.eclipse.oomph.setup.createsyncproject.feature.group"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/oomph/base/LabelProvider">
    <details key="imageBaseURI" value="http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/plugins/org.eclipse.oomph.setup.createsyncproject.edit/icons/full/obj16"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="CreateSyncProjectTask" eSuperTypes="http://www.eclipse.org/oomph/setup/1.0#//SetupTask">
    <eAnnotations source="http://www.eclipse.org/oomph/setup/ValidTriggers">
      <details key="triggers" value="STARTUP MANUAL"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
