<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="NUOPC" nsURI="http://www.earthsystemcog.org/projects/nuopc"
    nsPrefix="nuopc">
  <eClassifiers xsi:type="ecore:EClass" name="NUOPCComponent" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NUOPCBaseModel" abstract="true" eSuperTypes="#//NUOPCComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="NUOPCDriver" eSuperTypes="#//NUOPCComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//NUOPCComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NUOPCModel" eSuperTypes="#//NUOPCBaseModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="NUOPCMediator" eSuperTypes="#//NUOPCBaseModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="NUOPCConnector" eSuperTypes="#//NUOPCComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//NUOPCBaseModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//NUOPCBaseModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NUOPCApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//NUOPCComponent" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
