/*
* generated by Xtext
*/
package org.earthsystemmodeling;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CupidLanguageUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.earthsystemmodeling.ui.internal.CupidLanguageActivator.getInstance().getInjector("org.earthsystemmodeling.CupidLanguage");
	}
	
}
